# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Anna-Elovenko/6c67794099e9885353137405cc056120/task1.ipynb
"""

import math
num_1=float(input('Interfacial tension [mN/m]='))
num_2=float(input('Radius [m]='))
num_3=float(input('Angle [deg]='))
num_4=math.radians(num_3)
num_5=math.cos(num_4)
cap_pressure=(2*num_1*num_5)/(1000*num_2)
print('Capillary pressure=',cap_pressure,'Pa')
num_6=float(input('Water density [kg/m3]='))
num_7=float(input('Fluid density [kg/m3]='))
height=cap_pressure/((num_6-num_7)*9.8)
print('Height=',height,'m')